---
title: "Course Project 2"
author: "Jorge Silva Guzman"
date: "2024-06-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Project 2


```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
```

# Loading the Data

First, we load the datasets from the NEI and SCC spreadsheets.

```{r}
# Notes:
# NEI$fips: 5-digit codes of counties; some values are "NA's" (need to parse); (some counties codes missing)
# NEI$SCC: 8-code character indicating source of measurement; looks good
# NEI$Pollutant,Emissions, type, year: looks good

NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")

# Notes:
# After examination, EI.Sector and SCC.Level.One look like good candidates for the description of sources
# Perhaps SCC.Level.One -- SCC.Level.Three can help us refine what type of descriptive data we are looking for

```


```{r, echo=FALSE}
View(NEI)
View(SCC)
```



```{r}
# Convert dataframes into tibbles 
NEI <- tibble(NEI)
NEI <- rename(NEI, Year = year)
SCC <- tibble(SCC)
```


```{r}
# Summarize total emissions by Year and plot
NEI |>
  group_by(Year) |>
  summarize(Emissions = sum(Emissions)/10^6) |>
  with(barplot(Emissions ~ Year,
            col = Year,
            main = "Total Emissions [PM 2.5] by Year",
            xlab = "Years",
            ylab = "Emissions [PM 2.5] (Millions of Tons)",
            ylim = c(0, 8)
            )
       )

ggsave("plot1.png")
```

```{r}

# Summarize total emissions for Baltimore City by Year and plot
NEIBaltimore <- filter(NEI, fips == "24510")

NEIBaltimore |>
  group_by(Year) |>
  summarize(Emissions = sum(Emissions)/10^2) |>
  with(barplot(Emissions ~ Year,
            col = Year,
            main = "Total Emissions [PM 2.5] in Baltimore City by Year",
            xlab = "Years",
            ylab = "Emissions [PM 2.5] (Hundreds of Tons)",
            ylim = c(0,max(Emissions))
            )
       )

ggsave("plot2.png")
```

```{r}
# Summarize total emissions by Type and Year
# Create a bar plot, faceting by type, and according to year

NEIBaltimoreFacet <- filter(NEI, fips == "24510") |>
  group_by(type, Year) |>
  summarize(Emissions = sum(Emissions)/100) 

ggplot(data = NEIBaltimoreFacet, aes(factor(Year), Emissions, fill=type)) + 
  geom_bar(stat = "Identity") +
  geom_text(data = NEIBaltimoreFacet, 
            aes(label = paste("(", as.character(trunc(Emissions*100,2)/100), ")", sep="")),
            nudge_y = 1,
            size=2) +
  facet_grid(~ type) +
  labs(x="Years", y = "Total Emissions [PM 2.5] (Hundreds of Tons)", title="Total Emissions [PM 2.5] in Baltimore City from 1999-2008", subtitle="Arranged by Type", fill = "Type")
  theme(plot.title = element_text(hjust = 0.5))
  
  ggsave("plot3.png")
```

```{r}
# Idea: Find all SCC's with Coal Combustion data; create a boolean mask for coal-combustion sources
# Extract all valid SCC's; filter NEI by SCC's using boolean mask
# Summarize total emissions by year
# Plot total emissions by Year

CombCoalMask <- with(SCC, (grepl("[Cc]omb", EI.Sector) == TRUE &
           (
             grepl("[Cc]oal", SCC.Level.One) |
               grepl("[Cc]oal", SCC.Level.Two) |
               grepl("[Cc]oal", SCC.Level.Three) |
               grepl("[Cc]oal", SCC.Level.Four)
           )
         )
         )

NEICombCoal <- NEI[NEI$SCC %in% SCC[CombCoalMask,]$SCC,]

NEICombCoal |> 
  group_by(Year) |>
  summarize(Emissions = sum(Emissions)/100000) |>
  ggplot(aes(factor(Year), Emissions, fill=factor(Year))) +
  geom_bar(stat = "identity") +
  ylim(0, 8) +
  geom_text(
            aes(label = paste("(", as.character(trunc(Emissions*100,2)/100), ")", sep="")),
            nudge_y = 1,
            size=4) +
  labs(x="Years", y = "Emissions [PM 2.5] (in Hundred Thousand Tons)", title="Total Emissions [PM 2.5] from Coal-Combustion Sources in the US", subtitle="Years 1999-2008", fill = "Year")
  theme(plot.title = element_text(hjust = 0.5))
  
  ggsave("plot4.png")
```

```{r}

# Create another boolean mask for Motor-Vehicle sources
# Extract all valid SCC's; filter NEI by SCC's using boolean mask
# Summarize total emissions by year
# Plot total emissions by Year

MotorVehicleMask <- with(SCC, (grepl("(?=.*[Mm]obile)(?=.*[Vv]ehicle)", EI.Sector, perl=TRUE) 
         )
         )

SCCMask = SCC[MotorVehicleMask,]$SCC
NEIBaltMotorVehicle <- NEIBaltimore[NEIBaltimore$SCC %in% SCCMask,]

NEIBaltMotorVehicle |>
  group_by(Year) |>
  summarize(Emissions = sum(Emissions)) |>
  ggplot(aes(factor(Year), Emissions, fill=factor(Year))) +
  geom_bar(stat="identity") +
  geom_text(
            aes(label = paste("(", as.character(trunc(Emissions*100,2)/100), ")", sep="")),
            nudge_y = 18,
            size=4) +
  ylim(0,370) +
  labs(x="Years", y = "Emissions [PM 2.5] (in Tons)", title="Total Emissions [PM 2.5] from Motor-Vehicle Sources in Baltimore City", subtitle="Years 1999-2008", fill = "Year") +
  theme(plot.title = element_text(hjust = 0.5))
  
ggsave("plot5.png")
```

```{r}
# Create filter for motor vehicle emissions in LA County and Baltimore City
NEIBaltLAMotorVehicle <- filter(NEI, fips== "24510" | fips == "06037") 
NEIBaltLAMotorVehicle <- NEIBaltLAMotorVehicle[NEIBaltLAMotorVehicle$SCC %in% SCCMask,]

# Compute total emissions by fips and Year and create summary tibble
# Plot data as a bar graph by year, grouped by fips

NEIBaltLAMotorVehicle |> group_by(fips, Year) |>
  summarize(Emissions = sum(Emissions)) |>
  ggplot(aes(factor(Year), Emissions, fill=fips)) +
  geom_bar(position="dodge", stat="identity") +
  geom_text(
            aes(x = factor(Year), y = Emissions,
            label = paste("(", as.character(trunc(Emissions*100,2)/100), ")", sep="")),
            position=position_dodge(width=0.9),
            vjust = -0.5,
            size=4) +
  labs(x = "Years", y="Emissions [PM 2.5] (in Tons)", 
       title="Total Emissions [PM 2.5], Baltimore City vs. Los Angeles", 
       subtitle="Years 1999-2008", fill="City") +
  scale_fill_discrete(labels=c("LA", "Baltimore\nCity"))

ggsave("plot6.png")
```


